env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[13b0ab7b5b9b4c3f8684696a67a639bae5a3fa51e0e2d683b851c4223a664e40cf52726fac61e8a7fafee1eacc8491a4]"
    bot_api: "ENCRYPTED[886a60d75eef6e237f90ff5122dec9494303b3f1af75a0d5bf719db4c2b82f5dc3992f58be2fc5b450491aacb14af18d]"
    tg_id: "ENCRYPTED[e562662ba14aaa631d770f14f73b72eae16a7ea0bc6b99f45588d99066948cc4a19a0e0ab613c004aebf42f4b6ef5f17]"

task:
    name: xdroid-CAF
    timeout_in: 120m
    container:
      image: inok2341/builder:latest
      cpu: 8
      memory: 32G      

    rclone_setup_script:
      - mkdir -p ~/.config/rclone
      - echo "$rclone_config" > ~/.config/rclone/rclone.conf
    download_ccache_background_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Download ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - df -h && free -h && nproc && cat /etc/os* && env
      - rclone copy ramadhannangga:xdroid-CAF/ccache.tar.gz /tmp -P
      - cd /tmp
      - time tar xf ccache.tar.gz
      - rm -rf ccache.tar.gz
    sync_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Sync ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - git config --global  user.name "ramadhannangga"
      - git config --global  user.email "ramadhananggayudhanto@gmail.com"
      - export KBUILD_BUILD_USER=ramadhannangga
      - export KBUILD_BUILD_HOST=irisprjkt
      - mkdir -p /tmp/rom # Where to sync source
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/xdroid-CAF/xd_manifest -b eleven -g default,-device,-mips,-darwin,-notdefault
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8
      - git clone --depth=1 https://github.com/ramadhannangga/kernel_asus_sdm660 --single-branch -b master kernel/asus/sdm660
      - git clone --depth=1 https://github.com/ramadhannangga/vendor_asus --single-branch vendor/asus
      - git clone --depth=1 https://github.com/ramadhannangga/device_asus_sdm660-common --single-branch device/asus/sdm660-common
      - git clone --depth=1 https://github.com/ramadhannangga/device_asus_X01BD --single-branch device/asus/X01BD
    monitor_background_script:
      - ./monitor
    build_script:
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Build ROM at $(date)&chat_id=${tg_id}&parse_mode=html"
      - ./build
      - time rclone copy /tmp/rom/out/error.log ramadhannangga: -P
    upload_rom_script:
      - ./uprom
    compress_ccache_script:    
      - ./tarccache
    upload_ccache_script:
      - cd /tmp
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Uploading ccache at $(date)&chat_id=${tg_id}&parse_mode=html"
      - time rclone copy ccache.tar.gz ramadhannangga:xdroid-CAF -P 
      - curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Upload ccache done at $(date)&chat_id=${tg_id}&parse_mode=html"
