#!/bin/bash

cd /tmp

curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Compress ccache start at $(date)&chat_id=${tg_id}&parse_mode=html"

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

curl -s "https://api.telegram.org/bot${bot_api}/sendmessage" --data "text=Compress ccache done at $(date)&chat_id=${tg_id}&parse_mode=html"
